require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, min_ios_version_supported
prepare_react_native_project!


target 'FocusbearHackathon' do
  config = use_native_modules!

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'


  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FocusbearHackathonTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    # Comment out or remove this workaround if it's undefined
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
