require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'FocusbearHackathon' do
  config = use_native_modules!

  # Include DoubleConversion podspec
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'

  # Disable Hermes by setting hermes_enabled to false
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false, # Disable Hermes here
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Explicitly include react-native-screens
  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'FocusbearHackathonTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    # Commented out workaround for Xcode 12.5 M1 if undefined
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end



